### ISSUE TITLE
Write Tests For leapforg-ui

### ISSUE THREAD

**Issue by YrrepNoj** [defenseunicorns/leapfrogai-ui#70]
We currently do not have any tests written for the leapfrog-ui repository. We need a series of robust tests so we can be more confident in our software updates to this repository.

```[tasklist]
### Tasks
- [ ] Write unit tests that cover the svelte UI
- [ ] Write e2e tests that validate the leapfrog-ui Zarf package can be deployed and run successfully
- [ ] Create workflows that execute these tests and add branch protection rules that prevent PRs from being merged until they pass.
```
